### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by VickyBOSS** [shan-shaji/chalkdart#17]
```
final ch = Chalk();
print(ch.red('red text', ftFace: ChalkFtFace.italic));
```

I am creating a flutter app and I tried to implement this but it is not working

**Comment by shan-shaji** [comment]
Hey @VickyBOSS ,  sorry for the inconvenience caused. 
which IDE are you using? 

I am currently changing the implementation of this package. Will publish the newer version in 1 week. 

You can use [tint](https://pub.dev/packages/tint) as an alternative to this.

**Comment by VickyBOSS** [comment]
Vs code

**Comment by shan-shaji** [comment]
ok, will fix the issues soon

**Comment by VickyBOSS** [comment]
🙏

**Comment by shan-shaji** [comment]
Hey @VickyBOSS ,

Could you please check if the issue still persists? I have updated the package. The new version is `v1.1.5`
If the issue still persists let me know.

**Comment by VickyBOSS** [comment]
No, it doesn't.

I have tested it in debug console, powershell and git bash in VSCode but
nowhere it is working. What platform are you using?

By the way it is a nice package if it works

**Comment by shan-shaji** [comment]
I am using windows, but i am getting output in vs code.

Can you check it by running the project in example folder?

**Comment by VickyBOSS** [comment]
What Do you use? debug console or powershell or cmd for output

**Comment by shan-shaji** [comment]
I am using PowerShell, also tested in cmd. It's working for me i couldn't reproduce the issue.

**Comment by VickyBOSS** [comment]
I'll check it out try to figure it out. thanks for responding

**Comment by shan-shaji** [comment]
ok, As of now I am closing this issue if someone else faces the same issue I will reopen this.
